# Generated by Django 5.1.2 on 2024-10-30 15:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowRoom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(default='image.png', null=True, upload_to='')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DISABLE', 'DISABLE')], default='ACTIVE', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('loginId', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], default='FEMALE', max_length=20)),
                ('userType', models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], default='USER', max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DISABLE', 'DISABLE')], default='ACTIVE', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='company',
        ),
        migrations.RemoveField(
            model_name='carphoto',
            name='car',
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('colors', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=1, max_digits=8)),
                ('weight', models.IntegerField(default=0, null=True)),
                ('announcedDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('launchDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('screenWidth', models.DecimalField(decimal_places=1, max_digits=8)),
                ('screenHeight', models.DecimalField(decimal_places=1, max_digits=8)),
                ('width', models.DecimalField(decimal_places=1, max_digits=8)),
                ('height', models.DecimalField(decimal_places=1, max_digits=8)),
                ('length', models.DecimalField(decimal_places=1, max_digits=8)),
                ('dimentionUnit', models.CharField(choices=[('mm', 'mm'), ('cm', 'cm')], default='mm', max_length=20)),
                ('ram', models.IntegerField(default=0, null=True)),
                ('ramUnit', models.CharField(choices=[('MB', 'MB'), ('GB', 'GB'), ('TB', 'TB')], default='GB', max_length=20)),
                ('rom', models.IntegerField(default=0, null=True)),
                ('romUnit', models.CharField(choices=[('MB', 'MB'), ('GB', 'GB'), ('TB', 'TB')], default='GB', max_length=20)),
                ('bluetooth', models.CharField(max_length=200)),
                ('btVersion', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('wifi', models.CharField(max_length=200)),
                ('wifiVersion', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('frontCams', models.IntegerField(default=0, null=True)),
                ('fCam1Res', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('fCam2Res', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('fCam3Res', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('fCamFlash', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=20)),
                ('backCams', models.IntegerField(default=0, null=True)),
                ('bCam1Res', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('bCam2Res', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('bCam3Res', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('bCam4Res', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('bCamFlash', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=20)),
                ('fm', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=20)),
                ('sims', models.IntegerField(default=1, null=True)),
                ('sim1Network', models.CharField(choices=[('GSM', 'GSM'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G')], default='4G', max_length=10)),
                ('sim2Network', models.CharField(choices=[('GSM', 'GSM'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G')], default='4G', max_length=10)),
                ('sim3Network', models.CharField(choices=[('GSM', 'GSM'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G')], default='4G', max_length=10)),
                ('sim4Network', models.CharField(choices=[('GSM', 'GSM'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G')], default='4G', max_length=10)),
                ('battery', models.IntegerField(default=0, null=True)),
                ('photo', models.ImageField(default='image.png', null=True, upload_to='')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('OLD', 'OLD'), ('DISCONTINUED', 'DISCONTINUED')], default='NEW', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowRoom.brand')),
            ],
            options={
                'ordering': ['announcedDate'],
            },
        ),
        migrations.CreateModel(
            name='MobilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='image.png', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowRoom.mobile')),
            ],
            options={
                'ordering': ['-created', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowRoom.mobile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowRoom.user')),
            ],
            options={
                'ordering': ['-created', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowRoom.mobile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowRoom.user')),
            ],
            options={
                'ordering': ['-created', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowRoom.mobile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowRoom.user')),
            ],
            options={
                'ordering': ['-created', '-updated'],
            },
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarPhoto',
        ),
    ]
