# Generated by Django 5.1.2 on 2024-10-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowRoom', '0002_brand_user_remove_car_company_remove_carphoto_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='photo',
            field=models.ImageField(default='no-image.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mobilephoto',
            name='photo',
            field=models.ImageField(default='no-image.png', null=True, upload_to=''),
        ),
    ]
